[package]
name = "bevy_mesh_terrain"
description = "A simple and ergonomic heightmap terrain plugin for Bevy game engine"
version = "0.4.1"
edition = "2021"
authors = [ "ethereumdegen" ]
license = "MIT"
readme = "readme.md"
repository = "https://github.com/ethereumdegen/bevy_mesh_terrain"
exclude = [ "/assets/", "/examples/" ]
keywords = [ "terrain" , "bevy" ]


[dependencies]
anyhow = "1.0.75"
bevy = "0.12.0"
futures-lite = "1.13.0"
image = "0.24.7" 
thiserror = "1.0.48"
 
[[example]]
name = "basic"
path = "examples/basic.rs"


