[package]
name = "bevy_mesh_terrain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11"
image = "0.24.7"



[[example]]
name = "basic"
path = "examples/basic.rs"


