[package]
name = "bevy_mesh_terrain"
description = "A simple and ergonomic heightmap terrain plugin for bevy game engine"
version = "0.3.3"
edition = "2021"
author = "ethereumdegen"
license = "MIT"
readme="readme.md"
repository ="https://github.com/ethereumdegen/bevy_mesh_terrain"
keywords=["terrain","bevy"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
bevy = "0.11.2"
futures-lite = "1.13.0"
image = "0.24.7" 
thiserror = "1.0.48"
 
[[example]]
name = "basic"
path = "examples/basic.rs"


